### PR TITLE
Question about config code

### PR DESCRIPTION
**Pull request by taoteg**
This is more a discussion point than a PR.

I notice that we are splitting out a common.env file for the shared tags.

Isn't it easier to simply have one .env file with ALL the settings per $ENV HOST (which would match the sample.env file above) and eliminate maintaining the common.env file? I know it is not 100% DRY that way, but this is very short config and seems inefficient (opening a second file for 2 settings values) at this scale.

If common.env is going to be maintained, what is the intended practice for which of these sample.env values should go into that file instead of the $ENV.env file? There are enough deployments building up that we need to align on a consistent best practice for configuration.

### CODE REVIEW

**Comment by taoteg** [comment]
Follow on question - in theor it is possible to use different versions of camino on each target host, meaning could dev use Camino v2.0, pprd use Camino v2.1 and prod use Camino v2.2. That would mean only the dockerhub repo and image names are left in common.env. feels over-engineered at that point.

**Comment by rstijerina** [comment]
> This is more a discussion point than a PR.
> 
> I notice that we are splitting out a common.env file for the shared tags.
> 
> Isn't it easier to simply have one .env file with ALL the settings per $ENV HOST (which would match the sample.env file above) and eliminate maintaining the common.env file? I know it is not 100% DRY that way, but this is very short config and seems inefficient (opening a second file for 2 settings values) at this scale.
> 
> If common.env is going to be maintained, what is the intended practice for which of these sample.env values should go into that file instead of the $ENV.env file? There are enough deployments building up that we need to align on a consistent best practice for configuration.

I think that's a good point. It's more straightforward with one configuration file for each environment, without a `common.env`. If the commonalities far outpaced the distinctions, then I think a `common.env` would have a better place, but as it is it's not needed and over-dried.

**Comment by taoteg** [comment]
Yeah, I didn't know if there was "more to come" and I just didn't know it or is this is pretty much it, in which case I think a single file per $ENV would be more manageable.

We are also diverging across portals for what goes in which file already, so I thought it would be nice to normalize this before we start migrating even more portals to Corev2 and this deployment workflow.

**Comment by taoteg** [comment]
In the Jenkins script we could remove the common.env line, one less moving part.

```
### Source environment env file to get $CAMINO_VERSION
source camino/common.env
source camino/$Environment.env
```

**Comment by rstijerina** [comment]
Implemented.

**Pull request closed without merging**
